/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Capa_Cliente;

/**
 *
 * @author needa
 */
public class frm_MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form frmMenuPrincipal
     */
    Thread hilo;
    public frm_MenuPrincipal() {
        initComponents();
        hilo = new Thread();
        hilo.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblUsuarioActivo = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblFecha1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuSistema = new javax.swing.JMenu();
        mnuSCerrarSesion = new javax.swing.JMenuItem();
        mnuMantenimiento = new javax.swing.JMenu();
        mnuMHorario = new javax.swing.JMenuItem();
        mnuMDocente = new javax.swing.JMenuItem();
        mnuMAlumno = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        mnu_OAsesoria = new javax.swing.JMenuItem();
        mnu_OJurado = new javax.swing.JMenuItem();
        mnu_OAuditoria = new javax.swing.JMenuItem();
        mnu_OTesis = new javax.swing.JMenuItem();
        mnu_OSustentacion = new javax.swing.JMenuItem();
        mnu_ODocumento = new javax.swing.JMenuItem();
        mnuReporte = new javax.swing.JMenu();
        rTesisMes = new javax.swing.JMenuItem();
        rTesisPasar = new javax.swing.JMenuItem();
        rTesisEstado = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menú Principal");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Usuario.png"))); // NOI18N
        jLabel1.setText("Usuario :");

        lblUsuarioActivo.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/fecha.png"))); // NOI18N
        jLabel3.setText("Fecha :");

        lblFecha.setText("------------------");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Hora.png"))); // NOI18N
        jLabel5.setText("Hora :");

        lblFecha1.setText("------------------");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblUsuarioActivo, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(167, 167, 167)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblFecha1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(lblFecha)
                            .addComponent(jLabel5)
                            .addComponent(lblFecha1)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblUsuarioActivo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(23, 23, 23))
        );

        jMenuBar1.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jMenuBar1.setInheritsPopupMenu(true);

        mnuSistema.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        mnuSistema.setText("Sistema");

        mnuSCerrarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/cerrar.png"))); // NOI18N
        mnuSCerrarSesion.setText("Cerrar Sesion");
        mnuSCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSCerrarSesionActionPerformed(evt);
            }
        });
        mnuSistema.add(mnuSCerrarSesion);

        jMenuBar1.add(mnuSistema);

        mnuMantenimiento.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        mnuMantenimiento.setText("Mantenimiento");

        mnuMHorario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/horario.png"))); // NOI18N
        mnuMHorario.setText("Horario");
        mnuMHorario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuMHorarioActionPerformed(evt);
            }
        });
        mnuMantenimiento.add(mnuMHorario);

        mnuMDocente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/profesor.png"))); // NOI18N
        mnuMDocente.setText("Docente");
        mnuMDocente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuMDocenteActionPerformed(evt);
            }
        });
        mnuMantenimiento.add(mnuMDocente);

        mnuMAlumno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/alumno.png"))); // NOI18N
        mnuMAlumno.setText("Alumno");
        mnuMAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuMAlumnoActionPerformed(evt);
            }
        });
        mnuMantenimiento.add(mnuMAlumno);

        jMenuBar1.add(mnuMantenimiento);

        jMenu3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenu3.setText("Operaciones");

        mnu_OAsesoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/asesoria.png"))); // NOI18N
        mnu_OAsesoria.setText("Asesoría");
        mnu_OAsesoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnu_OAsesoriaActionPerformed(evt);
            }
        });
        jMenu3.add(mnu_OAsesoria);

        mnu_OJurado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/jurado.png"))); // NOI18N
        mnu_OJurado.setText("Asignar jurado");
        mnu_OJurado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnu_OJuradoActionPerformed(evt);
            }
        });
        jMenu3.add(mnu_OJurado);

        mnu_OAuditoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/auditoria.png"))); // NOI18N
        mnu_OAuditoria.setText("Auditoría");
        mnu_OAuditoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnu_OAuditoriaActionPerformed(evt);
            }
        });
        jMenu3.add(mnu_OAuditoria);

        mnu_OTesis.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/tesis.png"))); // NOI18N
        mnu_OTesis.setText("Tesis");
        mnu_OTesis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnu_OTesisActionPerformed(evt);
            }
        });
        jMenu3.add(mnu_OTesis);

        mnu_OSustentacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/sustentacion.png"))); // NOI18N
        mnu_OSustentacion.setText("Sustentación");
        mnu_OSustentacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnu_OSustentacionActionPerformed(evt);
            }
        });
        jMenu3.add(mnu_OSustentacion);

        mnu_ODocumento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/documento.png"))); // NOI18N
        mnu_ODocumento.setText("Documento");
        mnu_ODocumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnu_ODocumentoActionPerformed(evt);
            }
        });
        jMenu3.add(mnu_ODocumento);

        jMenuBar1.add(jMenu3);

        mnuReporte.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        mnuReporte.setText("Reporte");

        rTesisMes.setText("Reporte de tesis por sustentar en el presente año según un mes");
        rTesisMes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rTesisMesActionPerformed(evt);
            }
        });
        mnuReporte.add(rTesisMes);

        rTesisPasar.setText("Reporte de tesis por pasar el plazo");
        rTesisPasar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rTesisPasarActionPerformed(evt);
            }
        });
        mnuReporte.add(rTesisPasar);

        rTesisEstado.setText("Reporte de tesis aprobadas o rechazadas según rango de años");
        rTesisEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rTesisEstadoActionPerformed(evt);
            }
        });
        mnuReporte.add(rTesisEstado);

        jMenuItem1.setText("Reporte de Docentes sin Rol");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        mnuReporte.add(jMenuItem1);

        jMenuBar1.add(mnuReporte);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(367, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getAccessibleContext().setAccessibleName("frm_MenuPrincipal");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rTesisMesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rTesisMesActionPerformed
        jd_ReporteTesisMes obj = new jd_ReporteTesisMes(this,true);
        obj.setLocationRelativeTo(this);
        obj.setVisible(true);
    }//GEN-LAST:event_rTesisMesActionPerformed

    private void mnuMHorarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuMHorarioActionPerformed
        jd_Horario obj = new jd_Horario(this,true);
        obj.setLocationRelativeTo(this);
        obj.setVisible(true);
    }//GEN-LAST:event_mnuMHorarioActionPerformed

    private void mnuMDocenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuMDocenteActionPerformed
        jd_Docente obj = new jd_Docente(new javax.swing.JDialog(),true);
        obj.setLocationRelativeTo(this);
        obj.setVisible(true);
    }//GEN-LAST:event_mnuMDocenteActionPerformed

    private void mnuMAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuMAlumnoActionPerformed
        jd_Alumno obj = new jd_Alumno();
        obj.setLocationRelativeTo(this);
        obj.setVisible(true);
    }//GEN-LAST:event_mnuMAlumnoActionPerformed

    private void mnu_OAsesoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnu_OAsesoriaActionPerformed
        // TODO add your handling code here:
        jd_Asesoria obj = new  jd_Asesoria(this, true);
        obj.setLocationRelativeTo(obj);
        obj.setVisible(true);
        
    }//GEN-LAST:event_mnu_OAsesoriaActionPerformed

    private void mnu_ODocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnu_ODocumentoActionPerformed

    }//GEN-LAST:event_mnu_ODocumentoActionPerformed

    private void mnu_OTesisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnu_OTesisActionPerformed
        // TODO add your handling code here:
        
        jd_Tesis obj = new jd_Tesis(new javax.swing.JDialog(), true);
        obj.setLocationRelativeTo(this);
        obj.setVisible(true);
    }//GEN-LAST:event_mnu_OTesisActionPerformed

    private void mnu_OSustentacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnu_OSustentacionActionPerformed
        // TODO add your handling code here:
        jd_Sutentacion obj = new jd_Sutentacion();
        obj.setLocationRelativeTo(this);
        obj.setVisible(true);
    }//GEN-LAST:event_mnu_OSustentacionActionPerformed

    private void mnu_OJuradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnu_OJuradoActionPerformed

    }//GEN-LAST:event_mnu_OJuradoActionPerformed

    private void mnu_OAuditoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnu_OAuditoriaActionPerformed
        jd_Auditoria obj = new jd_Auditoria(this,true);
        obj.setLocationRelativeTo(this);
        obj.setVisible(true);
    }//GEN-LAST:event_mnu_OAuditoriaActionPerformed

    private void rTesisPasarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rTesisPasarActionPerformed
        jd_ReporteTesisPasar obj = new jd_ReporteTesisPasar(this,true);
        obj.setLocationRelativeTo(this);
        obj.setVisible(true);
    }//GEN-LAST:event_rTesisPasarActionPerformed

    private void rTesisEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rTesisEstadoActionPerformed
        jd_ReporteTesisEstado obj = new jd_ReporteTesisEstado(this,true);
        obj.setLocationRelativeTo(this);
        obj.setVisible(true);
    }//GEN-LAST:event_rTesisEstadoActionPerformed

    private void mnuSCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSCerrarSesionActionPerformed
        System.exit(0);
    }//GEN-LAST:event_mnuSCerrarSesionActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        jd_ReporteDocente obj = new jd_ReporteDocente(this,true);
        obj.setLocationRelativeTo(this);
        obj.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblFecha1;
    private javax.swing.JLabel lblUsuarioActivo;
    private javax.swing.JMenuItem mnuMAlumno;
    private javax.swing.JMenuItem mnuMDocente;
    private javax.swing.JMenuItem mnuMHorario;
    private javax.swing.JMenu mnuMantenimiento;
    private javax.swing.JMenu mnuReporte;
    private javax.swing.JMenuItem mnuSCerrarSesion;
    private javax.swing.JMenu mnuSistema;
    private javax.swing.JMenuItem mnu_OAsesoria;
    private javax.swing.JMenuItem mnu_OAuditoria;
    private javax.swing.JMenuItem mnu_ODocumento;
    private javax.swing.JMenuItem mnu_OJurado;
    private javax.swing.JMenuItem mnu_OSustentacion;
    private javax.swing.JMenuItem mnu_OTesis;
    private javax.swing.JMenuItem rTesisEstado;
    private javax.swing.JMenuItem rTesisMes;
    private javax.swing.JMenuItem rTesisPasar;
    // End of variables declaration//GEN-END:variables
}
