/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Capa_Cliente;

import Capa_Datos.clsJDBC;
import Capa_Negocio.clsAmbiente;
import Capa_Negocio.clsSustentacion;
import Capa_Negocio.clsTesis;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author USER
 */
public class jd_Sutentacion extends javax.swing.JFrame {

    public static clsTesis tesis_seleccionada;
    public static int alumnoid;
    
    public jd_Sutentacion() {
        initComponents();
        try {           
            //listarCombos();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error al listar Combos");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanel2 = new javax.swing.JPanel();
        btnModificar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cboHora_Inicio = new javax.swing.JComboBox<>();
        btnSalir = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        cboDesicion = new javax.swing.JComboBox<>();
        cboCalificacion = new javax.swing.JComboBox<>();
        cboHora_Fin = new javax.swing.JComboBox<>();
        dcFecha = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtComentarios = new javax.swing.JTextArea();
        chkEstado = new javax.swing.JCheckBox();
        btnCancelar = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lblAlumno = new javax.swing.JLabel();
        lblTesis = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Mantenimiento de Ambiente");
        setBackground(new java.awt.Color(255, 255, 51));

        jPanel2.setBackground(new java.awt.Color(88, 111, 124));
        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, java.awt.Color.darkGray, java.awt.Color.darkGray));
        jPanel2.setForeground(new java.awt.Color(34, 116, 165));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnModificar.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/modificar.png"))); // NOI18N
        btnModificar.setText("Modificar");
        btnModificar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        jPanel2.add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(252, 457, 130, -1));

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(244, 244, 249));
        jLabel2.setText("Fecha:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 101, -1, 25));

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(244, 244, 249));
        jLabel3.setText("Hora:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 150, 48, 25));

        jLabel5.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(244, 244, 249));
        jLabel5.setText("Calificación:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 187, 104, 25));

        jLabel6.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(244, 244, 249));
        jLabel6.setText("Comentarios:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 223, 104, 25));

        jLabel8.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(244, 244, 249));
        jLabel8.setText("Estado");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 387, 66, 25));

        cboHora_Inicio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "07:00", "08:00", "09:00", "10:00", "11:00", "12:00", "13:00", "14:00", "15:00", "16:00", "17:00", "18:00", "19:00", "20:00", "21:00", "22:00", "23:00", " " }));
        jPanel2.add(cboHora_Inicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 143, 83, 32));

        btnSalir.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/cerrar_mantenimiento.png"))); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jPanel2.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(252, 506, 130, -1));

        btnGuardar.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/nuevo.png"))); // NOI18N
        btnGuardar.setText("Nuevo");
        btnGuardar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel2.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 456, 130, 40));

        jLabel9.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(244, 244, 249));
        jLabel9.setText("Decisión:");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(335, 338, -1, 25));

        cboDesicion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Unanime", "Mayoria" }));
        jPanel2.add(cboDesicion, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 336, 225, 32));

        cboCalificacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Malo", "Regular", "Bueno", "Muy Bueno" }));
        jPanel2.add(cboCalificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 185, 225, 32));

        cboHora_Fin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "07:00", "08:00", "09:00", "10:00", "11:00", "12:00", "13:00", "14:00", "15:00", "16:00", "17:00", "18:00", "19:00", "20:00", "21:00", "22:00", "23:00", " " }));
        jPanel2.add(cboHora_Fin, new org.netbeans.lib.awtextra.AbsoluteConstraints(316, 143, 85, 32));
        jPanel2.add(dcFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 96, 225, 28));

        txtComentarios.setColumns(20);
        txtComentarios.setRows(5);
        jScrollPane1.setViewportView(txtComentarios);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 230, 225, -1));

        chkEstado.setText("(Vigente)");
        jPanel2.add(chkEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 386, 225, 30));

        btnCancelar.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/eliminar.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel2.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 506, 130, -1));

        jLabel10.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(244, 244, 249));
        jLabel10.setText("Alumno:");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 18, -1, -1));

        jLabel11.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(244, 244, 249));
        jLabel11.setText("Tesis:");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 53, -1, 25));

        lblAlumno.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        lblAlumno.setForeground(new java.awt.Color(244, 244, 249));
        jPanel2.add(lblAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 220, 25));

        lblTesis.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        lblTesis.setForeground(new java.awt.Color(244, 244, 249));
        jPanel2.add(lblTesis, new org.netbeans.lib.awtextra.AbsoluteConstraints(377, 53, 24, 25));

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("-");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(286, 148, 12, -1));
        jPanel2.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 59, 220, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 466, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 597, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        limpiar();
        jd_BuscarAlumno.Sus_funcNuevo = false;
        jd_BuscarAlumno.Sus_funcModificar = false;
        btnGuardar.setText("Nuevo");
        btnModificar.setEnabled(true);
        btnGuardar.setEnabled(true);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        try {
            if (lblAlumno.getText().equalsIgnoreCase("")) {
                limpiar();
                btnModificar.setEnabled(false);
                jd_BuscarAlumno.Sus_funcNuevo = true;
                jd_BuscarAlumno objJD = new jd_BuscarAlumno(new javax.swing.JDialog(), true);
                objJD.setLocationRelativeTo(null);
                objJD.setVisible(true);
            } else {
                if (btnGuardar.getText().equals("Nuevo")) {
                    limpiar();
                    dcFecha.requestFocus();
                    btnGuardar.setText("Guardar");
                } else if (btnGuardar.getText().equals("Guardar")) {
                    if (!txtComentarios.getText().equalsIgnoreCase("")) {
                        btnGuardar.setText("Nuevo");

                        clsSustentacion objS = new clsSustentacion();
                        objS.setId(clsSustentacion.generarCodigo());
                        objS.setFecha(new java.sql.Date(dcFecha.getDate().getTime()));

                        SimpleDateFormat df = new SimpleDateFormat("hh:mm");
                        String cadena_HoraInicio = cboHora_Inicio.getSelectedItem().toString();
                        java.util.Date dt_inicio = df.parse(cadena_HoraInicio);
                        objS.setHora_inicio(new java.sql.Time(dt_inicio.getTime()));

                        String cadena_HoraFin = cboHora_Fin.getSelectedItem().toString();
                        java.util.Date dt_fin = df.parse(cadena_HoraInicio);
                        objS.setHora_fin(new java.sql.Time(dt_fin.getTime()));

                        objS.setCalificacion(cboCalificacion.getSelectedItem().toString());
                        objS.setComentarios(txtComentarios.getText());
                        objS.setDecision(cboDesicion.getSelectedItem().toString());
                        //objS.setAmbiente((clsAmbiente) cboAmbiente.getSelectedItem());
                        objS.setEstado(chkEstado.isSelected());
                        objS.registrar(alumnoid);
                        limpiar();
                        btnModificar.setEnabled(true);
                        alumnoid = -1;
                        JOptionPane.showMessageDialog(this, "Sustentación agregada correctamente");
                    }
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al Guardar Sustentación");
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnModificarActionPerformed

    public void limpiar() {
        try {
            lblAlumno.setText("");
            lblTesis.setText("");
            dcFecha.setDate(clsJDBC.fecha_actual());
            cboHora_Inicio.setSelectedIndex(0);
            cboHora_Fin.setSelectedIndex(0);
            cboCalificacion.setSelectedIndex(0);
            txtComentarios.setText("");
            cboDesicion.setSelectedIndex(0);
            //cboAmbiente.setSelectedIndex(-1);
            chkEstado.setSelected(true);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error al limpiar");
        }
    }
    /*
    private void listarCombos() throws Exception {

        try {
            cboAmbiente.removeAllItems();
            for (clsAmbiente a : clsAmbiente.listar()) {
                cboAmbiente.addItem(a);
            }

        } catch (Exception ex) {
            throw ex;
        }
    }
    */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    public static javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnSalir;
    public static javax.swing.JComboBox<String> cboCalificacion;
    public static javax.swing.JComboBox<String> cboDesicion;
    public static javax.swing.JComboBox<String> cboHora_Fin;
    public static javax.swing.JComboBox<String> cboHora_Inicio;
    public static javax.swing.JCheckBox chkEstado;
    public static com.toedter.calendar.JDateChooser dcFecha;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField2;
    public static javax.swing.JLabel lblAlumno;
    public static javax.swing.JLabel lblTesis;
    public static javax.swing.JTextArea txtComentarios;
    // End of variables declaration//GEN-END:variables
}
