/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Capa_Cliente;

import Capa_Datos.clsJDBC;
import Capa_Negocio.clsAlumno;
import Capa_Negocio.clsTesis;
import javax.swing.JOptionPane;

/**
 *
 * @author USER
 */
public class jd_Tesis extends javax.swing.JDialog {

    public static int alumno_seleccionado;

    public jd_Tesis(javax.swing.JDialog parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanel2 = new javax.swing.JPanel();
        lblAlumno = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtTema = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtResolucion_Jurado = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        dcFecha_Jurado = new com.toedter.calendar.JDateChooser();
        btnSustentacion = new javax.swing.JButton();
        txtNota = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnArchivo = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        txtResolucion_Asesor = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        dcFecha_Asesor = new com.toedter.calendar.JDateChooser();
        jLabel13 = new javax.swing.JLabel();
        dcFecha_Sustentacion = new com.toedter.calendar.JDateChooser();
        txtResolucion_Sustentacion = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        chkEstado = new javax.swing.JCheckBox();
        lblEstadoArchivo = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        txtTitulo1 = new javax.swing.JTextField();

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Mantenimiento de Tesis");
        setBackground(new java.awt.Color(255, 255, 51));

        jPanel2.setBackground(new java.awt.Color(88, 111, 124));
        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, java.awt.Color.darkGray, java.awt.Color.darkGray));
        jPanel2.setForeground(new java.awt.Color(34, 116, 165));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblAlumno.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jPanel2.add(lblAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 40, 255, 25));

        btnSalir.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/cerrar_mantenimiento.png"))); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSalir.setMaximumSize(null);
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jPanel2.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 340, 130, 40));

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(244, 244, 249));
        jLabel2.setText("Titulo:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 61, 25));

        jLabel5.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(244, 244, 249));
        jLabel5.setText("Tema:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 61, 25));

        txtTema.setPreferredSize(new java.awt.Dimension(30, 22));
        txtTema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTemaActionPerformed(evt);
            }
        });
        jPanel2.add(txtTema, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, 255, 30));

        jLabel6.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(244, 244, 249));
        jLabel6.setText("Resolución Jurado:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, -1, 25));

        txtResolucion_Jurado.setPreferredSize(new java.awt.Dimension(30, 22));
        jPanel2.add(txtResolucion_Jurado, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, 255, 30));

        jLabel7.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(244, 244, 249));
        jLabel7.setText("Estado:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 530, 63, 25));

        btnGuardar.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/nuevo.png"))); // NOI18N
        btnGuardar.setText("Nuevo");
        btnGuardar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnGuardar.setMaximumSize(null);
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel2.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 110, 130, 35));

        btnModificar.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/modificar.png"))); // NOI18N
        btnModificar.setText("Modificar");
        btnModificar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnModificar.setMaximumSize(null);
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        jPanel2.add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 220, 130, 35));

        jLabel8.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(244, 244, 249));
        jLabel8.setText("Nota:");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 58, 25));

        jLabel9.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(244, 244, 249));
        jLabel9.setText("Fecha Jurado:");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, 107, 25));
        jPanel2.add(dcFecha_Jurado, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 230, 255, 30));

        btnSustentacion.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnSustentacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/editorial.png"))); // NOI18N
        btnSustentacion.setText("Sustentación");
        btnSustentacion.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSustentacion.setMaximumSize(null);
        btnSustentacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSustentacionActionPerformed(evt);
            }
        });
        jPanel2.add(btnSustentacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 160, 130, 40));
        jPanel2.add(txtNota, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 150, 53, 30));

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(244, 244, 249));
        jLabel3.setText("Archivo:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 470, 130, 25));

        btnArchivo.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnArchivo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/libro.png"))); // NOI18N
        btnArchivo.setText("Subir");
        btnArchivo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnArchivoActionPerformed(evt);
            }
        });
        jPanel2.add(btnArchivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 470, 256, 30));

        btnBuscar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/buscarMan.png"))); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.setMaximumSize(null);
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        jPanel2.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 50, 130, 35));

        jLabel11.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(244, 244, 249));
        jLabel11.setText("Resolución Asesor:");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, -1, 25));

        txtResolucion_Asesor.setPreferredSize(new java.awt.Dimension(30, 22));
        txtResolucion_Asesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtResolucion_AsesorActionPerformed(evt);
            }
        });
        jPanel2.add(txtResolucion_Asesor, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 270, 255, 30));

        jLabel12.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(244, 244, 249));
        jLabel12.setText("Fecha Asesor:");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 320, 107, 25));
        jPanel2.add(dcFecha_Asesor, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 310, 256, 30));

        jLabel13.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(244, 244, 249));
        jLabel13.setText("Fecha Sustentación:");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 420, 168, 25));
        jPanel2.add(dcFecha_Sustentacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 420, 256, 30));

        txtResolucion_Sustentacion.setPreferredSize(new java.awt.Dimension(30, 22));
        txtResolucion_Sustentacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtResolucion_SustentacionActionPerformed(evt);
            }
        });
        jPanel2.add(txtResolucion_Sustentacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 350, 255, 30));

        jLabel14.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(244, 244, 249));
        jLabel14.setText("Resolución Sustentación:");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 190, 40));

        chkEstado.setText("(Vigente)");
        jPanel2.add(chkEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 530, 256, 30));

        lblEstadoArchivo.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        lblEstadoArchivo.setForeground(new java.awt.Color(244, 244, 249));
        lblEstadoArchivo.setText("(Estado del archivo)");
        jPanel2.add(lblEstadoArchivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 500, 149, 25));

        jLabel4.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(244, 244, 249));
        jLabel4.setText("Alumno:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, -1, 25));

        btnCancelar.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/eliminar.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCancelar.setMaximumSize(null);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel2.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 280, 130, 40));

        txtTitulo1.setPreferredSize(new java.awt.Dimension(30, 22));
        txtTitulo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTitulo1ActionPerformed(evt);
            }
        });
        jPanel2.add(txtTitulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, 255, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 754, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 606, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        try {            
            if (lblAlumno.getText().equalsIgnoreCase("")) {
                limpiar();
                btnModificar.setEnabled(false);
                btnSustentacion.setEnabled(false);
                jd_BuscarAlumno.funcNuevo = true;
                jd_BuscarAlumno objJD = new jd_BuscarAlumno(new javax.swing.JDialog(), true);
                objJD.setLocationRelativeTo(null);
                objJD.setVisible(true);                               
            } else {                
                registrarTesis();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al Guardar Tesis");
        }


    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // TODO add your handling code here:
        try {
            btnGuardar.setEnabled(false);
            btnSustentacion.setEnabled(false);            
            jd_BuscarAlumno.funcModificar = true;            
            jd_BuscarAlumno objJD = new jd_BuscarAlumno(new javax.swing.JDialog(), true);
            objJD.setLocationRelativeTo(null);
            objJD.setVisible(true); 
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al Modificar Tesis");
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void txtTemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTemaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTemaActionPerformed

    private void btnSustentacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSustentacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSustentacionActionPerformed

    private void btnArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnArchivoActionPerformed
        // TODO add your handling code here:
        //jd_DocumentoTesis objManPropiedad = new jd_DocumentoTesis(null, true);
        //objManPropiedad.setLocationRelativeTo(this);
        //objManPropiedad.setVisible(true);
    }//GEN-LAST:event_btnArchivoActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed

        jd_BuscarAlumno.funcNuevo = true;
        jd_BuscarAlumno objJD = new jd_BuscarAlumno(new javax.swing.JDialog(), true);
        objJD.setLocationRelativeTo(null);
        objJD.setVisible(true);
        /*
        try {
            String DNI = txtDNI.getText();
            clsDocente docente = clsDocente.buscar_DNI(DNI);
            if(txtDNI.equals("")){
                txtDNI.requestFocus();
                JOptionPane.showMessageDialog(this, "Escriba un DNI para buscar");
            } else if (validarCadena(DNI) == false || DNI.length() > 8){
                JOptionPane.showMessageDialog(this, "DNI no válido");
            } else if (docente != null){
                txtNombre.setText(docente.getNombre());
                txtApellido.setText(docente.getApellido());
                dcFechaNacimiento.setDate(docente.getFecha_nacimiento());
                txtDireccion.setText(docente.getDireccion());
                txtCorreo.setText(docente.getCorreo());
                if(docente.getEstado().equalsIgnoreCase("A")){
                    cboEstado.setSelectedIndex(0);
                }else{
                    cboEstado.setSelectedIndex(1);
                }
            }else{
                JOptionPane.showMessageDialog(this, "DNI no existe");
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error al buscar Docente");
        }
         */
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void txtResolucion_AsesorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtResolucion_AsesorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtResolucion_AsesorActionPerformed

    private void txtResolucion_SustentacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtResolucion_SustentacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtResolucion_SustentacionActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        limpiar();
        jd_BuscarAlumno.funcNuevo = false;
        jd_BuscarAlumno.funcModificar = false;
        btnGuardar.setText("Nuevo");
        btnGuardar.setEnabled(true);
        btnSustentacion.setEnabled(true);
        btnModificar.setEnabled(true);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void txtTitulo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTitulo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTitulo1ActionPerformed

    public void limpiar() {
        try {
            lblAlumno.setText("");
            txtTitulo1.setText("");
            txtTema.setText("");
            txtNota.setText("");
            txtResolucion_Jurado.setText("");
            txtResolucion_Asesor.setText("");
            txtResolucion_Sustentacion.setText("");
            lblEstadoArchivo.setText("(Estado del archivo)");

            chkEstado.setSelected(true);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error al obtener fecha actual");
        }
    }

    public void limpiar2() {
        try {
            txtTitulo1.setText("");
            txtTema.setText("");
            txtNota.setText("");
            txtResolucion_Jurado.setText("");
            txtResolucion_Asesor.setText("");
            txtResolucion_Sustentacion.setText("");
            lblEstadoArchivo.setText("(Estado del archivo)");
            chkEstado.setSelected(true);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error al obtener fecha actual");
        }
    }

    public void registrarTesis() {
        try {
            if (btnGuardar.getText().equals("Nuevo")) {
                limpiar2();
                txtTitulo1.requestFocus();
                btnGuardar.setText("Guardar");
            } else if(btnGuardar.getText().equals("Guardar")) {
                if (!txtTitulo1.getText().equalsIgnoreCase("")){
                    btnGuardar.setText("Nuevo");
                    clsTesis objT = new clsTesis();
                    objT.setId(clsTesis.generarCodigo());
                    objT.setTitulo(txtTitulo1.getText());
                    objT.setTema(txtTema.getText());
                    objT.setFecha(clsJDBC.fecha_actual());
                    objT.setNota(Integer.parseInt(txtNota.getText()));
                    objT.setResolucionJurado(txtResolucion_Jurado.getText());
                    objT.setFecha_jurado(new java.sql.Date(dcFecha_Jurado.getDate().getTime()));
                    objT.setResolucionAsesor(txtResolucion_Asesor.getText());
                    objT.setFecha_asesor(new java.sql.Date(dcFecha_Asesor.getDate().getTime()));
                    objT.setResolucionSustentacion(txtResolucion_Sustentacion.getText());
                    objT.setFecha_sustentacion(new java.sql.Date(dcFecha_Sustentacion.getDate().getTime()));
                    objT.setUrl("url");// subir archivo
                    objT.setEstado(chkEstado.isSelected());
                    objT.setAlumno(clsAlumno.buscar(alumno_seleccionado));
                    objT.Registrar();
                    limpiar();
                    btnModificar.setEnabled(true);
                    btnSustentacion.setEnabled(true);
                    JOptionPane.showMessageDialog(this, "Tesis agregada correctamente");
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al registrar Tesis");
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnArchivo;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCancelar;
    public static javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnSustentacion;
    public static javax.swing.JCheckBox chkEstado;
    public static com.toedter.calendar.JDateChooser dcFecha_Asesor;
    public static com.toedter.calendar.JDateChooser dcFecha_Jurado;
    public static com.toedter.calendar.JDateChooser dcFecha_Sustentacion;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    public static javax.swing.JLabel lblAlumno;
    public static javax.swing.JLabel lblEstadoArchivo;
    public static javax.swing.JTextField txtNota;
    public static javax.swing.JTextField txtResolucion_Asesor;
    public static javax.swing.JTextField txtResolucion_Jurado;
    public static javax.swing.JTextField txtResolucion_Sustentacion;
    public static javax.swing.JTextField txtTema;
    public static javax.swing.JTextField txtTitulo1;
    // End of variables declaration//GEN-END:variables
}
